---
title: "LDA with morpho data playground"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 6
---

Playing around with LDA and geomorph data

# Packages and data

## Packages

```{r, message = FALSE}
library(ape)
library(geomorph)
library(MASS)
library(glmnet)
```

## Data

We can do this analysis on the "simple" `plethodon` dataset:

```{r}
## Loading the plethodon dataset
data(plethodon)

## Performing the GPA
procrustes <- geomorph::gpagen(plethodon$land, print.progress = FALSE)

## Sorting the species
Jord_sp <- which(plethodon$species == "Jord")
Teyah_sp <- which(plethodon$species == "Teyah")

## Naming the species in the procrustes object
Jord_sp_names <- paste0("Jord_", Jord_sp)
Teyah_sp_names <- paste0("Teyah_", Teyah_sp)
dimnames(procrustes$coords)[[3]] <- rep(NA, length(c(Jord_sp, Teyah_sp)))
dimnames(procrustes$coords)[[3]][Jord_sp] <- Jord_sp_names
dimnames(procrustes$coords)[[3]][Teyah_sp] <- Teyah_sp_names
```

# A PCA

```{r}
## Converting into a 2D matrix
procrustes_matrix <- geomorph::two.d.array(procrustes$coords)

## PCA
morphospace <- prcomp(procrustes_matrix)
```

We can then plot the PCA using the following plotting function (recycled below):

```{r}
## Plotting PCA function
#@param ordination is the PCA
#@param classifier is a list of different groups rows IDs to plot
#@param axis are the axes to plot
#@param cols are the plotting colours (should be equal in length to classifier argument)
#@param legend whether to plot the legend (default = TRUE)
#@param leg.pos if legend = TRUE, the legend position (default = "topleft")
#@param ... are passed to plot()
plot.pca <- function(ordination, classifier, axis = c(1, 2), cols,
                     legend = TRUE, leg.pos = "topleft", ...) {
    ## The data
    data <- ordination$x[, axis]

    ## The plot limits
    plot_lim <- range(data)

    ## The loadings
    load <- summary(ordination)$importance[2, axis]*100

    ## The plot
    plot(NULL, xlim = plot_lim, ylim = plot_lim,
        xlab = paste0("PC", axis[1], " (", load[1], "%)"),
        ylab = paste0("PC", axis[2], " (", load[2], "%)"),
        ...)

    ## Adding the points
    for(one_class in 1:length(classifier)) {
        ## Coordinates
        coordinates <- ordination$x[classifier[[one_class]], axis]
        if(length(coordinates) == 2) {
            points(x = coordinates[1], y = coordinates[2], pch = 19, col = cols[one_class])
        } else {
            points(coordinates, pch = 19, col = cols[one_class])
        }
    }

    ## Adding a legend
    legend(leg.pos, legend = names(classifier), pch = 19, col = cols, bty = "n")
}
```

```{r, fig.width = 8, fig.height = 8}
classifier <- list("Jord" = Jord_sp, "Teyah" = Teyah_sp)
plot.pca(morphospace, classifier = classifier, cols = c("orange", "blue"), main = "Tips only")
```


## LDA

```{r}
## SP classifier
test_sp <- data.frame(procrustes_matrix,
                      Sp = unlist(lapply(strsplit(rownames(procrustes_matrix), split = "_"),
                        function(x) return(x[1]))))


## Also add a fake (PCA) classifier

Iris <- data.frame(rbind(iris3[,,1], iris3[,,2], iris3[,,3]),
                   Sp = rep(c("s","c","v"), rep(50,3)))
train <- sample(1:150, 75)
table(Iris$Sp[train])
## your answer may differ
##  c  s  v
## 22 23 30
z <- MASS::lda(Sp ~ ., Iris, prior = c(1,1,1)/3, subset = train)
predict(z, Iris[-train, ])$class
##  [1] s s s s s s s s s s s s s s s s s s s s s s s s s s s c c c
## [31] c c c c c c c v c c c c v c c c c c c c c c c c c v v v v v
## [61] v v v v v v v v v v v v v v v
(z1 <- update(z, . ~ . - Petal.W.))



```


## Lasso

```{r}
library(glmnet)
x <- model.matrix(Salary~.-1, data = Hitters)
y <- Hitters$Salary

fit_ridge <- glmnet(x, y, alpha = 0) # Ridge
cv_ridge <- cv.glmnet(x, y, alpha = 0) # Cross validation

fit_lasso <- glmnet(x, y, alpha = 1) # Lasso
```
